=== jzarnikov/LSDC/docs/xsd/hierarchy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.infosys.tuwien.ac.at/lsds/hierarchy/" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.infosys.tuwien.ac.at/lsds/hierarchy/">


    <element name="hierarchy" type="tns:hierarchyType"></element>
    
    <complexType name="hierarchyType">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<element name="topic" type="tns:topicType"></element>
    	</sequence>
    </complexType>

    <complexType name="topicType">
    	<sequence>
    		<element name="topic" type="tns:topicType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>
</schema>

=== jzarnikov/LSDC/src/test/java/at/tuwien/lsdc/performance/performanceTestHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:hierarchy xmlns:tns="http://www.infosys.tuwien.ac.at/lsds/hierarchy/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.infosys.tuwien.ac.at/lsds/hierarchy/ ../../../../../../../docs/xsd/hierarchy.xsd ">
<tns:topic name="rootTopic">
	<tns:topic name="topic1">
		<tns:topic name="topic1-1">
			<tns:topic name="topic1-1-1">
				<tns:topic name="topic1-1-1-1"/>
				<tns:topic name="topic1-1-1-2"/>
				<tns:topic name="topic1-1-1-3"/>
			</tns:topic>
			<tns:topic name="topic1-1-2">
				<tns:topic name="topic1-1-2-1"/>
				<tns:topic name="topic1-1-2-2"/>
				<tns:topic name="topic1-1-2-3"/>
			</tns:topic>
			<tns:topic name="topic1-1-3">
				<tns:topic name="topic1-1-3-1"/>
				<tns:topic name="topic1-1-3-2"/>
				<tns:topic name="topic1-1-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic1-2">
			<tns:topic name="topic1-2-1">
				<tns:topic name="topic1-2-1-1"/>
				<tns:topic name="topic1-2-1-2"/>
				<tns:topic name="topic1-2-1-3"/>
			</tns:topic>
			<tns:topic name="topic1-2-2">
				<tns:topic name="topic1-2-2-1"/>
				<tns:topic name="topic1-2-2-2"/>
				<tns:topic name="topic1-2-2-3"/>
			</tns:topic>
			<tns:topic name="topic1-2-3">
				<tns:topic name="topic1-2-3-1"/>
				<tns:topic name="topic1-2-3-2"/>
				<tns:topic name="topic1-2-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic1-3">
			<tns:topic name="topic1-3-1">
				<tns:topic name="topic1-3-1-1"/>
				<tns:topic name="topic1-3-1-2"/>
				<tns:topic name="topic1-3-1-3"/>
			</tns:topic>
			<tns:topic name="topic1-3-2">
				<tns:topic name="topic1-3-2-1"/>
				<tns:topic name="topic1-3-2-2"/>
				<tns:topic name="topic1-3-2-3"/>
			</tns:topic>
			<tns:topic name="topic1-3-3">
				<tns:topic name="topic1-3-3-1"/>
				<tns:topic name="topic1-3-3-2"/>
				<tns:topic name="topic1-3-3-3"/>
			</tns:topic>
		</tns:topic>
	</tns:topic>
	<tns:topic name="topic2">
		<tns:topic name="topic2-1">
			<tns:topic name="topic2-1-1">
				<tns:topic name="topic2-1-1-1"/>
				<tns:topic name="topic2-1-1-2"/>
				<tns:topic name="topic2-1-1-3"/>
			</tns:topic>
			<tns:topic name="topic2-1-2">
				<tns:topic name="topic2-1-2-1"/>
				<tns:topic name="topic2-1-2-2"/>
				<tns:topic name="topic2-1-2-3"/>
			</tns:topic>
			<tns:topic name="topic2-1-3">
				<tns:topic name="topic2-1-3-1"/>
				<tns:topic name="topic2-1-3-2"/>
				<tns:topic name="topic2-1-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic2-2">
			<tns:topic name="topic2-2-1">
				<tns:topic name="topic2-2-1-1"/>
				<tns:topic name="topic2-2-1-2"/>
				<tns:topic name="topic2-2-1-3"/>
			</tns:topic>
			<tns:topic name="topic2-2-2">
				<tns:topic name="topic2-2-2-1"/>
				<tns:topic name="topic2-2-2-2"/>
				<tns:topic name="topic2-2-2-3"/>
			</tns:topic>
			<tns:topic name="topic2-2-3">
				<tns:topic name="topic2-2-3-1"/>
				<tns:topic name="topic2-2-3-2"/>
				<tns:topic name="topic2-2-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic2-3">
			<tns:topic name="topic2-3-1">
				<tns:topic name="topic2-3-1-1"/>
				<tns:topic name="topic2-3-1-2"/>
				<tns:topic name="topic2-3-1-3"/>
			</tns:topic>
			<tns:topic name="topic2-3-2">
				<tns:topic name="topic2-3-2-1"/>
				<tns:topic name="topic2-3-2-2"/>
				<tns:topic name="topic2-3-2-3"/>
			</tns:topic>
			<tns:topic name="topic2-3-3">
				<tns:topic name="topic2-3-3-1"/>
				<tns:topic name="topic2-3-3-2"/>
				<tns:topic name="topic2-3-3-3"/>
			</tns:topic>
		</tns:topic>
	</tns:topic>
	<tns:topic name="topic3">
		<tns:topic name="topic3-1">
			<tns:topic name="topic3-1-1">
				<tns:topic name="topic3-1-1-1"/>
				<tns:topic name="topic3-1-1-2"/>
				<tns:topic name="topic3-1-1-3"/>
			</tns:topic>
			<tns:topic name="topic3-1-2">
				<tns:topic name="topic3-1-2-1"/>
				<tns:topic name="topic3-1-2-2"/>
				<tns:topic name="topic3-1-2-3"/>
			</tns:topic>
			<tns:topic name="topic3-1-3">
				<tns:topic name="topic3-1-3-1"/>
				<tns:topic name="topic3-1-3-2"/>
				<tns:topic name="topic3-1-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic3-2">
			<tns:topic name="topic3-2-1">
				<tns:topic name="topic3-2-1-1"/>
				<tns:topic name="topic3-2-1-2"/>
				<tns:topic name="topic3-2-1-3"/>
			</tns:topic>
			<tns:topic name="topic3-2-2">
				<tns:topic name="topic3-2-2-1"/>
				<tns:topic name="topic3-2-2-2"/>
				<tns:topic name="topic3-2-2-3"/>
			</tns:topic>
			<tns:topic name="topic3-2-3">
				<tns:topic name="topic3-2-3-1"/>
				<tns:topic name="topic3-2-3-2"/>
				<tns:topic name="topic3-2-3-3"/>
			</tns:topic>
		</tns:topic>
		<tns:topic name="topic3-3">
			<tns:topic name="topic3-3-1">
				<tns:topic name="topic3-3-1-1"/>
				<tns:topic name="topic3-3-1-2"/>
				<tns:topic name="topic3-3-1-3"/>
			</tns:topic>
			<tns:topic name="topic3-3-2">
				<tns:topic name="topic3-3-2-1"/>
				<tns:topic name="topic3-3-2-2"/>
				<tns:topic name="topic3-3-2-3"/>
			</tns:topic>
			<tns:topic name="topic3-3-3">
				<tns:topic name="topic3-3-3-1"/>
				<tns:topic name="topic3-3-3-2"/>
				<tns:topic name="topic3-3-3-3"/>
			</tns:topic>
		</tns:topic>
	</tns:topic>
</tns:topic>
</tns:hierarchy>

=== jzarnikov/LSDC/src/test/java/at/tuwien/lsdc/xml/hierarchyTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:hierarchy xmlns:tns="http://www.infosys.tuwien.ac.at/lsds/hierarchy/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../../../../../../main/java/at/tuwien/lsdc/xml/hierarchy.xsd">
<tns:topic name="rootTopic">
	<tns:topic name="network">
		<tns:topic name="in-trafic"/>
		<tns:topic name="out-trafic"/>
		<tns:topic name="latency"/>
	</tns:topic>
	<tns:topic name="performance">
		<tns:topic name="cpu">
			<tns:topic name="load"/>
			<tns:topic name="free-cores"/>
		</tns:topic>
	</tns:topic>
</tns:topic>
</tns:hierarchy>
